networks:
  htpcnet:
    name: htpcnet

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT_PATH}/config/jellyfin:/config
      - ${ROOT_PATH}/complete/tv:/data/tvshows
      - ${ROOT_PATH}/complete/movies:/data/movies

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 8112:8112
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT_PATH}/downloads:/downloads # downloads folder
      - ${ROOT_PATH}/config/deluge:/config # config files

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT_PATH}/config/prowlarr:/config

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT_PATH}/config/sonarr:/config # config files
      - ${ROOT_PATH}/complete/tv:/tv # tv shows folder
      - ${ROOT_PATH}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT_PATH}/config/radarr:/config # config files
      - ${ROOT_PATH}/complete/movies:/movies # movies folder
      - ${ROOT_PATH}/downloads:/downloads # download folder

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT_PATH}/config/bazarr:/config # config files
      - ${ROOT_PATH}/complete/movies:/movies # movies folder
      - ${ROOT_PATH}/complete/tv:/tv # tv shows folder

  falre_solverr:
    container_name: falre_solverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    networks:
      - htpcnet
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - TZ=${TZ}
